sources:
  - name: Books
    handler:
      openapi:
        baseUrl: http://localhost:3002/
        # below, this allows Mesh to translate the OpenAPI JSON definition to a GraphQL Schema.
        source: ../books-service/openapi3-definition.json
transforms:
  - filterSchema:
      filters:
        - Query.!book
  - rename:
      renames:
        - from:
            type: Query
            field: categories
          to:
            type: Query
            field: booksCategories
